version: "3"
services:
  redis-master-1:
    container_name: redis-master-1
    image: redis
    volumes:
      - ./redis/config/redis-master-1.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7101:7101
      - 7102:7102
      - 7103:7103

  redis-master-2:
    network_mode: "service:redis-master-1"
    container_name: redis-master-2
    image: redis
    volumes:
      - ./redis/config/redis-master-2.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  redis-master-3:
    network_mode: "service:redis-master-1"
    container_name: redis-master-3
    image: redis
    volumes:
      - ./redis/config/redis-master-3.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  redis-slave-1:
    network_mode: "service:redis-master-1"
    container_name: redis-slave-1
    image: redis
    volumes:
      - ./redis/config/redis-slave-1.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  redis-slave-2:
    network_mode: "service:redis-master-1"
    container_name: redis-slave-2
    image: redis
    volumes:
      - ./redis/config/redis-slave-2.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  redis-slave-3:
    network_mode: "service:redis-master-1"
    container_name: redis-slave-3
    image: redis
    volumes:
      - ./redis/config/redis-slave-3.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  redis-cluster-entry:
    network_mode: "service:redis-master-1"
    image: redis
    container_name: redis-cluster
    command: redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7101 127.0.0.1:7102 127.0.0.1:7103 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3

  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elk/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - default_bridge

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.8.1
    build:
      context: ./elk
    volumes:
      - ./elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    environment:
      - "xpack.monitoring.enabled=false"
    depends_on:
      - elasticsearch
    networks:
      - default_bridge

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24